meson: Fix GCC 14 build
> In file included from ../libavdevice/alldevices.c:65:
>
> ./libavdevice/indev_list.c:2:5: error: initialization of ‘const AVInputFormat *’ from incompatible pointer type ‘const FFInputFormat *’ [-Wincompatible-pointer-types]

See https://gcc.gnu.org/gcc-14/porting_to.html

Part-of: <https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg/-/merge_requests/167>
(cherry picked from commit ab164b1d29d423cabf25a6f2be2688956393d34f)